server:
  port: 1862
spring:
  application:
    name: redline-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}