server:
  port: 1001
spring:
  application:
    name: redline-gateway
  cloud:
    nacos:
      server-addr: ${REDLINE_NACOS_SERVER_ADDR:127.0.0.1:1848}
      username: ${REDLINE_NACOS_USERNAME:nacos}
      password: ${REDLINE_NACOS_PASSWORD:nacos}
      discovery:
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
      config:
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        file-extension: yml
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
