services:
#  todo redline-user-service
  redline-user-db:
    image: mysql:8.0.31
    container_name: redline-user-db
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
    volumes:
      - ./volumes/db/data:/var/lib/mysql
      - ./volumes/db/config:/etc/mysql/conf.d
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: redline
