version: "3.9"
services:
#  todo redline-user-service
  redline-user-db:
    image: mysql:8.0.31
    container_name: redline-user-db
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
    volumes:
      - ./volumes/db/data:/var/lib/mysql
      - ./volumes/db/config:/etc/mysql/conf.d
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - "1102:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redline_user
      MYSQL_USER: redline
      MYSQL_PASSWORD: redline
